### ISSUE TITLE
Support for an alternate key ring (.gpg)

### ISSUE THREAD

**Issue by 1ccb** [heilingbrunner/vscode-gnupg-tool#1]
Congratulations on this extension! It's very useful.  Do you have a plan to support alternate key ring locations because currently it appears to only take the default, trustdb.gpg.

**Comment by heilingbrunner** [comment]
Why not ? Any propsals how to do this ?

**Comment by heilingbrunner** [comment]
I think this should be done with workspace settings. I will check.

**Comment by heilingbrunner** [comment]
I chose a different approach. If the extension detects a directory with the required key ring files and directories, then all commands are executed with the homedir parameter.

**Comment by 1ccb** [comment]
Not sure I understand - how does the extension detect a directory with a key ring?  My key ring is not necessarily on one of the project directories. It seems like the vscode setting  is the way to go (and  alternatively supporting GNUPGHOME env variable)
