### ISSUE TITLE
Unable to use extension remotely

### ISSUE THREAD

**Issue by digilink** [heilingbrunner/vscode-gnupg-tool#12]
I use vscode on a remote linux machine and access from Windows 10. I installed the GnuPG-Tool remotely so I could encrypt/decrypt files from my Windows 10 workstation. 

If I highlight some text and select "Encrypt Selection w/Passphrase" it fails and displays: 

"GnuPG: Encryption failed! gpg: symmetric encryption of '[stdin]' failed: Operation cancelled"

Is this a supported scenario? I don't see any settings that would impact this, but I'm entirely not sure.

**Comment by heilingbrunner** [comment]
Is gnupg installed on the remote system ?

**Comment by digilink** [comment]
Yes, installed and working fine: 

sbrown@rorschach:~$ which gpg
/usr/bin/gpg
sbrown@rorschach:~$ gpg --version
gpg (GnuPG) 2.2.19
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/sbrown/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by heilingbrunner** [comment]
I will check this scenario. Thanks.

**Comment by heilingbrunner** [comment]
Yesterday i used my extension under Raspbian and i had some troubles too.
Do you have an aditional `PIN or pass-phrase dialog for GnuPG` installed ?

**Comment by heilingbrunner** [comment]
Now I checked same remote situation and I get the same error.

**Comment by heilingbrunner** [comment]
A short test you can try

> echo "test" | gpg --clear-sign --pinentry-mode loopback

which runs in the terminal and asks the pass-phrase on the terminal. This should work.
