### ISSUE TITLE
Unable to select recipient(s)

### ISSUE THREAD

**Issue by GeertHauwaerts** [heilingbrunner/vscode-gnupg-tool#14]
```
GnuPG version 2.2.23
VS Code version: 1.49.3
GnuPG-Tool version: 1.3.8
```

Hey, I am trying to encrypt a string. When I select the option `Encrypt Selection w/ Recipients` it does not allow me to select any recipient.

![image](https://user-images.githubusercontent.com/7902071/95220646-59d33180-07ff-11eb-8450-1dbb954e2e75.png)

When I enter the email address it tell me that the recipient cannot be found.

![image](https://user-images.githubusercontent.com/7902071/95220732-6fe0f200-07ff-11eb-9b18-86690620c419.png)

I am able to encrypt via the command line using the email address `geert@hauwaerts.be`.

![image](https://user-images.githubusercontent.com/7902071/95220914-a0289080-07ff-11eb-8f43-f7c427256058.png)
![image](https://user-images.githubusercontent.com/7902071/95221043-b898ab00-07ff-11eb-85eb-10de749b2a89.png)

> Note: Despite the warning, the file gets encrypted, and I can also decrypt it.

I have two keys listed with an e-mail address via `-list-secret-keys` and `--list-public-keys`, so I assumed they would listed in VS Code as encryption recipients.

**Comment by GeertHauwaerts** [comment]
The Jose Valecillos `valecillos.gpg` VS Code extension can see both recipients and encrypt the selected text. Hence I think the issue is related to your plugin and not my GPG installation/configuration.

**Comment by heilingbrunner** [comment]
Hi,

i think it depends on the capabilities/attributes of your key(s).

For encryption with recipients, i only list keys which are not disabled (d), can encrypt (e) and is known (mfuws).

The fourth screenshot shows a message, that your key does not belongs to a named person (??).

Can you [generate](https://github.com/heilingbrunner/vscode-gnupg-tool/wiki/Generate-Key-(via-Terminal)) new test key and try with this key ?

**Comment by GeertHauwaerts** [comment]
Ok, I got it, after importing my key, I have to set the trust level to 5 or it will not appear. As per https://stackoverflow.com/questions/33361068/gnupg-there-is-no-assurance-this-key-belongs-to-the-named-user

Thanks for pushing me in the right direction :)

**Comment by heilingbrunner** [comment]
Thank you for your detailed response.
