### ISSUE TITLE
Allow menu option to "Re-Check" for running GPG Agent

### ISSUE THREAD

**Issue by Elte156** [heilingbrunner/vscode-gnupg-tool#15]
I set up my global git settings to GPG sign every commit.
I use this plugin to keep track of my GPG install and interface with VSCode.

- gpg (GnuPG) 2.2.22
- git version 2.18.0
- VSCode Version: 1.49.2

Here's what it looks like when the plugin detects my installed GPG
![image](https://user-images.githubusercontent.com/6825856/97358417-9da2df00-1871-11eb-846f-eb1a5ed60cf8.png)

**Problem**
There are some instances where the gpg-agent and the VSCode plugin will get out of sync.
It will display not available at the bottom and I am unable to commit anything because the git commands fail the gpg check.

I believe this is the message that returns:
https://github.com/heilingbrunner/vscode-gnupg-tool/blob/b5e42a0e12b0c798da0102f7f3f65944e8463520/src/extension.ts#L80-L83

**Temp Solution**
- Open up a separate terminal
- Kill the gpg-agent
- Then start the gpg-agent as a daemon
- Close VSCode
- Reopen VSCode

Is there a way to add an option to the plugin to recheck for a running gpg-agent as opposed to just at VSCode startup?

The perfect solution is to determine why the out-of-sync happens in the first place.

**Comment by heilingbrunner** [comment]
The extension uses the global available gpg. It uses the [gpg --version](https://github.com/heilingbrunner/vscode-gnupg-tool/wiki/Check-GnuPG) command to get the version. 
To kill the gpg-agent, you only have to use the [End Session](https://github.com/heilingbrunner/vscode-gnupg-tool/wiki/End-Session) command.
I don't know why the git command fails, because this is not part of the extension.
Can you use both commands from the terminal (inside/outside vscode) to verify the problem ?

**Comment by Elte156** [comment]
@heilingbrunner I will try your suggestion when this "not available" error happens and get back to you.

**Comment by Elte156** [comment]
@heilingbrunner Ok so it was only a matter of time until this issue popped up again. Here are the details.

I've had a long-running instance of VSCode (I don't turn my machine off nor close VSCode) and this appears at the bottom right.
![image](https://user-images.githubusercontent.com/6825856/97911522-63c25480-1d19-11eb-9683-917869ae2ed3.png)

If I open a new instance of VSCode (CMD + Shift + N), I see.
![image](https://user-images.githubusercontent.com/6825856/97911705-ba2f9300-1d19-11eb-9495-5f42073bee28.png)

I ran `gpg --version` inside the 'broken' VSCode terminal and outside iTerm terminal and it returns that GPG is avail.
```
$ gpg --version 
gpg (GnuPG) 2.2.22
libgcrypt 1.8.6
Copyright (C) 2020 Free Software Foundation, Inc.
...
```

I run the VSCode shortcut `GnuPG: Check GnuPG` and get:
![image](https://user-images.githubusercontent.com/6825856/97912090-4fcb2280-1d1a-11eb-9b0c-f598496e38ce.png)
Same with shortcuts `GnuPG: Environment ...` and `GnuPG: End Session`

I ran the kill command manually in the 'broken' VSCode terminal and it responded appropriately.
```console
$ gpg-connect-agent killagent /bye
gpg-connect-agent: no running gpg-agent - starting '/usr/local/Cellar/gnupg/2.2.22/bin/gpg-agent'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: connection to agent established
OK closing connection
```
Then I tried to run the VSCode shortcuts in the 'broken' VSCode terminal and I still get "GnuPG not available!".


The issue is only resolved if I close the VSCode instance and reopen the same project. So there's some out of sync issue going on.

**Comment by heilingbrunner** [comment]
Thank you for the detailed information.

Hm....
I have to check, when the version check is called again. It is called when the extension is activated on start up.

In the mean time i try to add two new commands, which are copied to the vscode terminal
1. `git config --global user.signinkey <xxxxx>` to make the key handling comfortable
2. `git config --global --unset user.signingkey` to revert this previous command

**Comment by heilingbrunner** [comment]
I am running vscode since several days on my Raspberry-Pi. No problems. ...
How to reproduce the failure ? Any guess ?

**Comment by Elte156** [comment]
The current device I am currently using is a MAC Mojave V10.14.4

I don't turn the machine off, but I do put it to sleep (close the laptop lid) every day.
I never close the VSCode instances either.

Perhaps there's some bug when the machine wakes up and re-init processes in VSCode?

**Comment by Elte156** [comment]
By the way. I found a much easier way to get around this issue. It's not a permanent fix, but it's much quicker than the temp solution I listed above.

Running this in VSCode will quickly reload the current instance and it fixes the GnuPG issue.
`>Developer:Reload Window`

**Comment by alfonmga** [comment]
I had the same issue on `macOS 11.4 (20F71)`. I fixed it by setting up the global environment variable `GNUPGHOME` to my GPG homedir `/Users/alfon/.gnupg` and finally it was detected by the extension.
