### ISSUE TITLE
configure to use WSL gpg

### ISSUE THREAD

**Issue by theflyingape** [heilingbrunner/vscode-gnupg-tool#17]
This extension runs as expected on a Chromebook with Debian Buster's gpg. But when using **Windows 10** and **WSL** installed (_using the Ubuntu distro_), it claims "gpg (GnuPG) is not available!"

The integrated terminal is configured to use the default shell: **WSL Bash - C:\WINDOWS\System32\wsl.exe**
```linux
$ gpg --version
gpg (GnuPG) 2.2.19
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/rhurst/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```
Can this support WSL?  We're not used to having developers load Windows binaries from external sources to secure files.  :)

**Comment by heilingbrunner** [comment]
I think this will not work, because VSCode runs still in Windows with a VSCode-Server, which runs in WSL. Commands without a gpg dialog will run, commands requiring pin-entry dialogs will fail. GnuPG cannot raise the pin-entry dialog from WSL in Windows.

Sorry.
