### ISSUE TITLE
Can not decrypt/encrypt any more with passphrases

### ISSUE THREAD

**Issue by feugy** [heilingbrunner/vscode-gnupg-tool#2]
Hello!

Since few versions of VSCode, it is impossible to decrypt encoded text (or file) with passphrase:
![image](https://user-images.githubusercontent.com/186268/61106303-026bd780-a47d-11e9-94af-e0310d442c6e.png)
It does not ask for input and shows an error.

Encrypting with passphrase does not work either: 
![image](https://user-images.githubusercontent.com/186268/61106461-89b94b00-a47d-11e9-9cbd-781f56510c2e.png)
It does not ask for input, shows a success message and produces an empty file.

I'm not 100% sure, but I think it started with VSCode version 1.35 or 1.36

**Comment by heilingbrunner** [comment]
Hello,
i see that you are using GnuPG v1. This version is outdated. I only used GnuPG v2.2. Have you tried GnuPG v2.2 ? It is still working with VSCode 1.36.

**Comment by heilingbrunner** [comment]
I will test GnuPG v1.4.

**Comment by heilingbrunner** [comment]
Support for GnuPG v1.4 integrated.
