### ISSUE TITLE
Feature Request: Re-interpret Markdown (and other) file contents after decryption

### ISSUE THREAD

**Issue by armnrd** [heilingbrunner/vscode-gnupg-tool#29]
I often use the extension to read encrypted Markdown files. For example, I open a file Document.md.asc, select all the text and decrypt it using "GnuPG: Decrypt Selection". After this happens, VSCode doesn't automatically reinterpret the file as a Markdown document, which means it doesn't have syntax highlighting and I cannot use Markdown editing shortcuts.

It would be useful to have the extension cause the contents of a file to be re-interpreted if I decrypt all of the file.

**Comment by heilingbrunner** [comment]
This is too difficult, because the decryption returns only text. ...

**Comment by armnrd** [comment]
All right, I will try and look for a way to trigger this automatically. There should be something in the API that achieves "automagically reinterpret contents of active editor".
