### ISSUE TITLE
vscode-gnupg-tool does not work on a Mac with latest GPG Suite

### ISSUE THREAD

**Issue by hoanga** [heilingbrunner/vscode-gnupg-tool#4]
When I tried to install a more recent release of this extension on a Mac using GPG Suite, the extension fails to detect the version of GPG installed.  It displays as _undefined.undefined.undefined_ in the status bar

After some investigating, it appears that the version header from GPG Suite version of GPG is slightly different from a typical installation of GPG.   See below for example version returned from GPG Suite GPG:

```
$ gpg --version | head -n 1
gpg (GnuPG/MacGPG2) 2.2.17
```

The vscode-gnupg-tool extension assumes a match for a version string header of the following form: 

> gpg (GnuPG)

This does not match the version returned from the GPG Suite version of GPG.   Because the check fails, calls for encrypting and decrypting via the GPG plugin will silently fail.

The following is a suggested patch fix.  The other option is to update the documentation to install a version of GPG that returns a version string that is expected:

```
diff --git a/src/utils.ts b/src/utils.ts
index bfd1cb0..2133ae8 100644
--- a/src/utils.ts
+++ b/src/utils.ts
@@ -147,6 +147,8 @@ export function linesToVersion(lines: string[]): string | undefined {
   for (let line of lines) {
     if (line.startsWith('gpg (GnuPG) ')) {
       return line.substr('gpg (GnuPG) '.length).trim();
+    } else if (line.startsWith('gpg (GnuPG/MacGPG2) ')) {
+      return line.substr('gpg (GnuPG/MacGPG2) '.length).trim();
     }
   }
   return undefined;

```

**Comment by heilingbrunner** [comment]
I will check as soon as possible on my Mac. Thank you.

**Comment by hoanga** [comment]
Thanks!

**Comment by heilingbrunner** [comment]
I took your code and checked it. Worked ! Thank you. 👍
