### ISSUE TITLE
Decrypt selection failed on macOS

### ISSUE THREAD

**Issue by scaba** [heilingbrunner/vscode-gnupg-tool#5]
**macOS**
Catalina 10.15.2 (19C57)

**VSCode**
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

**GnuPG-Tool**
v1.3.3

**GPG Suite** 
2019.1

When trying to "Decrypt selection" I get the following error:

`GnuPG: Decryption failed! Error: gpg: cannot open '/dev/tty': Device not configured`

GPG Suite is installed and I can decrypt the same cipher block on the command line. I uninstalled and reinstalled, restarting VSCode between each, and the issue persists.

**Comment by heilingbrunner** [comment]
Hi,
i have a Mac with this software
macOS: High Sierra 10.13.6
VSCode: 1.14.1
GnuPG-Suite: 2019.1
GnuPG: v2.2.17

I only installed the GPG Suite. The decryption has no problem. The vscode extension only uses plain gpg commands. Important here is that i try to support only v1.4 and v2.2. Other versions have reached the [**'end of life'**](https://gnupg.org/download/index.html).

Can you check which version of gpg runs on your system ? Please run command 'gpg --version' in the terminal.

**Comment by scaba** [comment]
I wonder if this is something Catalina introduced. This is the output of gpg --version (installed via Homebrew) :

gpg (GnuPG) 2.2.19
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/joefrancia/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

**Comment by heilingbrunner** [comment]
I think this '**GnuPG: Decryption failed! Error: gpg: cannot open '/dev/tty': Device not configured**' error is just a user right issue on your machine, which is not related to gnupg.
Does it work now ?

**Comment by scaba** [comment]
Still doesn't work with the same error. I haven't changed any rights on my Mac, though I do have System Integrity Protection disabled for some reason. Could that be an issue? 

Other functions of the extension work ok, like copy fingerprint to clipboard or copy GnuPG info. I assume that's because they don't need access to /dev/urandom or whatever. Encrypting a file from the command line also works ok, e.g. `gpg -r user@example.com -e file.txt`

**Comment by heilingbrunner** [comment]
My gpg installation comes from [gpgtools.org](https://gpgtools.org/). It still includes gpg version 2.2.17. I am not an expert for brew installations, but there may be the difference.
Can you check this installation from gpgtools ?

**Comment by scaba** [comment]
OK, uninstalled the Homebrew version and installed from gpgtools.org. I also re-enabled SIP in case that was messing with things. Now I get this error:

> GnuPG: Encryption failed! gpg: symmetric encryption of '[stdin]' failed: Operation cancelled

❯ gpg --version
gpg (GnuPG/MacGPG2) 2.2.17
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```
Home: /Users/XXXXXXX/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

The About box will not let me copy text, so here's a screenshot:

![image](https://user-images.githubusercontent.com/1500865/79769654-3f54dc80-82e1-11ea-93e0-aa3541a5ba5d.png)

**Comment by heilingbrunner** [comment]
Nearly the same set. Only macOS is different. My Mac is too old for the last upgrade.
But this looks to me like a privileg issue. Are you running as admin ? All operations are running via the stdin/stdout to/from gpg in the background. No magic.

![gpgsuite-info](https://user-images.githubusercontent.com/1827209/79870348-22a0cd80-83e3-11ea-8a29-3040019a5d3d.png)

Still no idea. Sorry.
