### ISSUE TITLE
how to enable explorer context menu?

### ISSUE THREAD

**Issue by John3** [heilingbrunner/vscode-gnupg-tool#7]
Hi!

There is a way to enable the the explorer context menu? I don't have it.

![image](https://user-images.githubusercontent.com/1057449/80284417-01422900-86e4-11ea-86a8-db5b860467b9.png)

GnuPG-Tool 1.3.4
VSCodium 1.44.2

![image](https://user-images.githubusercontent.com/1057449/80284428-0d2deb00-86e4-11ea-80e7-ecd64eb2fd6b.png)

Great extension 👍 😃

**Comment by heilingbrunner** [comment]
Hi !

i used the same VSCodium (unknown until now to me)

I selected a file in the left **explorer** view and then opened context menu. **This worked**.

![image](https://user-images.githubusercontent.com/1827209/80405770-5720f780-88c3-11ea-9396-9d2b8d381f64.png)

Opened the '**More Actions ...**' menu. **This worked**.

![image](https://user-images.githubusercontent.com/1827209/80406802-eaa6f800-88c4-11ea-8675-b33bb5cb1d26.png)


I see you tried to open the context menu from the **editor tab**. **This failed**.

I will check.

Thank you.

**Comment by heilingbrunner** [comment]
I added the context menu in **GnuPG-Tool 1.3.5**

![image](https://user-images.githubusercontent.com/1827209/80500808-edf6be00-896e-11ea-9b76-4f864daee402.png)

Correct ?

**Comment by John3** [comment]
Hey thanks a bunch man! :) yep eventually I saw it in the left explorer. I tried in the context menu because that was the way I saw in the readme.md file. Already see the commit https://github.com/heilingbrunner/vscode-gnupg-tool/commit/4754c7ae9dc13bd3c1cff953ae386947f4a2cbeb I think the issue can be closed now, or when you see fit. Thanks 👍
