### ISSUE TITLE
Enable wiki with how to use tutorial? or a FAQ?

### ISSUE THREAD

**Issue by John3** [heilingbrunner/vscode-gnupg-tool#8]
There are a few feature that I not sure how to use, sometime I don't have a lot of time to just poke around :( yeah I know maybe in few days I will use with all the function I need, but just saying...

Can you enable a wiki and add a few basic how to? hmm let me think... maybe a common use like encrypt for all your notes with a single password. Or a FAQ? if something don't work as expect after the installation, with a suggestion of how to fix it.

This will help any new user to user this great extension quickly

thank you

**Comment by heilingbrunner** [comment]
I will check how to create and manage a wiki here on github.

**Comment by heilingbrunner** [comment]
Done. Small wiki created.
Any questions ?

**Comment by John3** [comment]
Hey, I reviewed few topic it seems very good. Thank you this will help anyone just starting with you extension. I will read it. I'm pretty sure the issue can be closed.

Not sure where to ask this, or if this question should have is own "issue".  I'm using more this extension. There is a way to encrypt all the files? I was in a situation that needs to encrypt all the files inside a folder from my workspace.

My quick thinking was, 😅 first thought, right click the folder then "encrypt w/pass" but not, not work, it seems works directly in the file. My second thought was select all files using shift then right click "encrypt w/pass" but only encrypted the last file. My third thought was select all the files using shift but this time try to send a command from the prompt to encrypt but not work either. 🤣 

Thanks again 😉

**Comment by heilingbrunner** [comment]
Hi,
thank you for the comment. Please create a issue "Wiki issues", where we can collect all further wiki issues.

For your problem i recommend 7zip, or any other zip tool, with a passphrase. This **folder encryption** is nor intended.

**Encryption of a list of selected files** maybe possible. Please create new issue "Encrypt list of selected files" for this new issue.

Thanks.
