### ISSUE TITLE
Encrypt list of selected files

### ISSUE THREAD

**Issue by John3** [heilingbrunner/vscode-gnupg-tool#9]
Allow to select files (Maybe Ctrl or using Shift) from the "Explorer view" and then encrypt the selected files.

Related: https://github.com/heilingbrunner/vscode-gnupg-tool/issues/8#issuecomment-629874086

**Comment by heilingbrunner** [comment]
First I wanted to fix this feature with the __gpgtar__  command. But the __GpgEx__ extension in the [Gpg4win](https://www.gpg4win.de/index.html) software is more suitable for this use case. That is why this feature will not be implemented in the extension.
